name: Build Cache [using jupyter-book] for Windows
on:
  schedule:
    # Execute cache weekly at 3am on Monday
    - cron:  '0 3 * * 1'
  workflow_dispatch:  # Allows manual trigger if required

jobs:
  cache:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: "3.12"
          environment-file: environment.yml
          activate-environment: quantecon
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./ -W --keep-going
      - name: Upload Execution Reports (HTML)
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: execution-reports
          path: _build/html/reports
      - name: Upload "_build" folder (cache)
        uses: actions/upload-artifact@v5
        with:
          name: build-cache-windows
          path: _build
          include-hidden-files: true