name: Build HTML [using jupyter-book] and CN environment
on: [pull_request]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: "3.12"
          environment-file: environment-cn.yml
          activate-environment: quantecon
      - name: Graphics Support
        run: |
          sudo apt-get -qq update && sudo apt-get install -y graphviz
      - name: Install latex dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y     \
            texlive-latex-recommended \
            texlive-latex-extra       \
            texlive-fonts-recommended \
            texlive-fonts-extra       \
            texlive-xetex             \
            latexmk                   \
            xindy                     \
            dvipng                    \
            cm-super
      - name: Display Conda Environment Versions
        shell: bash -l {0}
        run: conda list
      - name: Display Pip Versions
        shell: bash -l {0}
        run: pip list
      - name: Download "build" folder (cache)
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: cache.yml
          branch: main
          name: build-cache
          path: _build
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./ -nW --keep-going
      - name: Upload Execution Reports (HTML)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: execution-reports
          path: _build/html/reports
